/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.algebra;

import hr.algebra.dal.MovieRepository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.dal.UserInterface;
import hr.algebra.model.AppAccessable;
import hr.algebra.model.User;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HT-ICT
 */
public class Zadatak extends javax.swing.JFrame implements AppAccessable {

    /**
     * Creates new form Zadatak
     */
    private static final String ADMIN_PANEL = "Admin panel";
    private static final String USER_PANEL = "User panel";

    private static MovieRepository repository;
    private static UserInterface userRepository;

    public Zadatak() {
        initComponents();
        try {
            init();
        } catch (Exception ex) {
            Logger.getLogger(Zadatak.class.getName()).log(Level.SEVERE, null, ex);
        }
        new AppAccessableDialog(this, true).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpContent = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tpContent.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1177, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpContent.getAccessibleContext().setAccessibleParent(tpContent);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zadatak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zadatak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zadatak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zadatak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zadatak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tpContent;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean selectUser(User user) {
        try {

            if (userRepository.selectUser(user).isPresent()) {
                if (userRepository.selectUser(user).get()) {
                    tpContent.add(ADMIN_PANEL, new AdminsPanel());
                    tpContent.add(ADMIN_PANEL, new ExitPanel());
                } else {
                    tpContent.add(USER_PANEL, new MenuPanel());
                }
                return true;
            }
        } catch (Exception ex) {
            Logger.getLogger(Zadatak.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    @Override
    public Boolean addUser(User user) {
        try {
            if (userRepository.addUser(user)) {
                tpContent.add(USER_PANEL, new MenuPanel());
                return true;
            }
        } catch (Exception ex) {
            Logger.getLogger(Zadatak.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    private void init() throws Exception {
        repository = RepositoryFactory.<MovieRepository>getRepository();
        userRepository = RepositoryFactory.<UserInterface>getRepository();
    }
}
